apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: hd719/complex-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST # name of the ENV variable
              value: redis-cluster-ip-service # how we are connecting to the service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD # the env variable and how the password will show up in the container, the name PGPASSWORD is not related to the secret
              valueFrom: # Get the value for this ENV variable from some config
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD # the key has to be the same that we used in the command to create the secret object
